# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Naman Gupta
email: namangt68@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://namangt68.github.io" # the base hostname & protocol for your site
github_username: namangt68
linkedin_username: namangt68
twitter_username: namangt68

# Build settings
markdown: kramdown
paginate: 5

gems:
  - jekyll-sitemap
